version: '3.9'
services:
  smartbrain-api:
    container_name: backend
    # image: node:16.17.1
    build: ./
    command: npm start
    working_dir: /usr/src/smartbrain-api
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_URI=postgres://tescrabnvuiapv:b34fc520dd257643ea8701864a11520e1af832d0e6d97cf99cd0071decd1bc9f@ec2-34-247-172-149.eu-west-1.compute.amazonaws.com:5432/de7k80budpklhf
      - API_KEY_CLARIFAI=2c8697350ea7401b889eea81bf05c715
      - PORT=3000
      - DATABASE_URL=postgres://tescrabnvuiapv:b34fc520dd257643ea8701864a11520e1af832d0e6d97cf99cd0071decd1bc9f@ec2-34-247-172-149.eu-west-1.compute.amazonaws.com:5432/de7k80budpklhf
      - REDIS_URI=redis://redis:6379
    volumes:
      - ./:/usr/src/smartbrain-api

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tescrabnvuiapv
      - POSTGRES_PASSWORD=b34fc520dd257643ea8701864a11520e1af832d0e6d97cf99cd0071decd1bc9f
      - POSTGRES_DB=de7k80budpklhf
      - POSTGRES_HOST=ec2-34-247-172-149.eu-west-1.compute.amazonaws.com

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_URI=redis://redis:6379
